// Generated events file
// This file is automatically generated by scripts/generate-events.js
// Do not edit manually

export const events = [
  {
    "title": "The Game",
    "icon": "🐈‍⬛",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "\"Hello, dear witch.  I am your familiar, the Black Cat.  It is from me that you get your magic.  Ensure you keep me satisfied, lest you risk losing my favor.\"",
        "choices": [
          {
            "text": "Continue.",
            "n": "1"
          },
          {
            "text": "I already know what to do.",
            "n": "4"
          }
        ]
      },
      {
        "id": "1",
        "type": "d",
        "p": "\"I have provided you with a magic dice.  Hover over it to see its faces.  There are three kinds of magic.\"<br><br>- DICE_FIRE_MAGIC is for fending off your enemies.<br>- DICE_HEART_MAGIC is for affecting people.<br>- DICE_GROW is for growing your garden.",
        "rolls": [
          "1 ANY"
        ],
        "pass": "2",
        "fail": "2"
      },
      {
        "id": "2",
        "type": "m",
        "p": "\"I am tasking you with running a potion shop: each day you will harvest magical herbs, mix potions, and deal with the many problems of the nearby villagers.\"<br><br>- You get <b>Herbs</b> by growing them in your garden.<br>- You get <b>Reagents</b> by buying them from a merchant.",
        "n": "3"
      },
      {
        "id": "3",
        "type": "m",
        "p": "\"Run this shop for <b>1 month</b> and you will have convinced me that you are a competent witch.  Then, and only then, I shall let you keep your magic.\"",
        "n": "4"
      },
      {
        "id": "4",
        "type": "m",
        "p": "\"Here are some materials to get you started.  Don't disappoint me.\"",
        "n": "eIntro"
      },
      {
        "id": "eIntro",
        "type": "end"
      }
    ],
    "vars": {}
  },
  {
    "title": "The Wizard",
    "icon": "🧙🏼‍♀️",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "An old wizard enters your shop. He challenges you to a duel, promising a great reward.<br><br>If you win: the wizard can teach you a new spell, and you get @A.<br>If you lose, the wizard takes @B.<br><br>You can sense the Black Cat observing you.",
        "choices": [
          {
            "text": "Accept! This guy's going down.<br>@A",
            "n": "1"
          },
          {
            "text": "Reject.",
            "n": "2"
          }
        ]
      },
      {
        "id": "2",
        "type": "m",
        "p": "The wizard leaves.",
        "n": "e"
      },
      {
        "id": "1",
        "type": "d",
        "p": "The wizard readies a magic spell!  You raise your hands...",
        "rolls": [
          "@A"
        ],
        "pass": "3",
        "fail": "4"
      },
      {
        "id": "3",
        "type": "m",
        "p": "Your spells clash in magnificent glory, and when the smoke clears you stand triumphant! The defeated wizard teaches you a new spell.<br><br>You can feel that the Black Cat appreciates your victory.",
        "mod": [
          "@A",
          "@C"
        ],
        "n": "e"
      },
      {
        "id": "4",
        "type": "m",
        "p": "Damn!  His spell was just too much for you to handle.  The smug wizard pockets his earnings before leaving. You feel the Black Cat is displeased.",
        "mod": [
          "-@B",
          "-@C"
        ],
        "n": "e"
      }
    ],
    "vars": {
      "@A": {
        "str": "1 EFFECT_FACE_ADD_FIRE"
      },
      "@B": {
        "str": "ALL GOLD"
      },
      "@C": {
        "str": "1 FAVOR_CAT"
      }
    }
  },
  {
    "title": "Gnome Thief",
    "icon": "👨",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "You wake up this morning to find a small gnome stealing from your garden!  With a fistful of herbs, he spots you and tries to run away as fast as his little feet can carry him.",
        "choices": [
          {
            "text": "Use your magic to threaten the gnome, but you may damage the herbs...<br>@A",
            "n": "1"
          },
          {
            "text": "Entice the gnome to give back the herbs.<br>@B",
            "n": "2"
          },
          {
            "text": "Let him take @C, but at least there'll be no ruckus.",
            "n": "fail"
          }
        ]
      },
      {
        "id": "1",
        "type": "d",
        "p": "You raise your hand and aim at the little fellow.",
        "rolls": [
          "@A"
        ],
        "pass": "1pass",
        "fail": "fail2"
      },
      {
        "id": "1pass",
        "type": "m",
        "p": "The gnome drops your herbs and runs off, but errant fire damages your garden.<br><br>In his haste, he dropped some gold on the ground.",
        "mod": [
          "-@D",
          "@R1"
        ],
        "n": "e"
      },
      {
        "id": "2",
        "type": "d",
        "p": "You call out to the gnome and attempt wrap your words with your magic.",
        "rolls": [
          "@B"
        ],
        "pass": "2pass",
        "fail": "fail2"
      },
      {
        "id": "2pass",
        "type": "m",
        "p": "The gnome timidly hands over the herbs and scampers off.<br><br>You notice some coins on the ground. He must have felt bad.",
        "mod": [
          "@R2"
        ],
        "n": "e"
      },
      {
        "id": "fail",
        "type": "m",
        "p": "@L",
        "mod": [
          "-@C"
        ],
        "n": "e"
      },
      {
        "id": "fail2",
        "type": "m",
        "p": "@L<br><br>The Black Cat is displeased with your failure.",
        "mod": [
          "-@C",
          "-@E"
        ],
        "n": "e"
      }
    ],
    "vars": {
      "@A": {
        "str": "FIRE(2)"
      },
      "@B": {
        "str": "HEART(1)"
      },
      "@C": {
        "str": "HERB(RAND2_4 y)"
      },
      "@D": {
        "str": "HERB(1 y)"
      },
      "@E": {
        "str": "1 FAVOR_CAT"
      },
      "@L": {
        "str": "The gnome slips away with your herbs."
      },
      "@R1": {
        "str": "GOLD(5)"
      },
      "@R2": {
        "str": "GOLD(9)"
      }
    }
  },
  {
    "title": "Unfortunate Evil",
    "icon": "💀",
    "children": [
      {
        "id": "0",
        "type": "m",
        "p": "Abruptly, an undead creature steps into your shop, raises a bony finger at you, and zaps you with a dark lightning.<br><br>The pain of it causes you to pass out. When you awaken, the creature is gone, but you feel... off.<br><br>Such is the peril of being a witch.",
        "mod": [
          "@A"
        ],
        "n": "e"
      }
    ],
    "vars": {
      "@A": {
        "str": "1 EFFECT_REPLACE_CURSE"
      }
    }
  },
  {
    "title": "Injured Dragon",
    "icon": "🐲",
    "children": [
      {
        "id": "S",
        "type": "m",
        "p": "A villager rushes into your shop. \"My pet dragon!\", he says, \"He's injured. Can you help?\"<br><br>You walk outside to see an irritated, tiny dragon with a gash across his body.  Smoke streams from its nostrils, ready to burn anything that comes too close.",
        "n": "0"
      },
      {
        "id": "0",
        "type": "ch",
        "p": "You know you can do this if you can get close.  You can sense the Black Cat observing you.",
        "choices": [
          {
            "text": "Try to calm the dragon down. @A",
            "n": "1"
          },
          {
            "text": "You have @B1; @L2",
            "conditionText": "HAS(@B1)",
            "n": "2a"
          },
          {
            "text": "You can mix<br>@B1. @L2",
            "conditionText": "HAS_I(@B1)",
            "n": "2b"
          },
          {
            "text": "Sorry, dragons are too dangerous.",
            "n": "3"
          }
        ]
      },
      {
        "id": "1",
        "type": "d",
        "p": "Carefully you step towards the dragon, readying your magic.",
        "rolls": [
          "@A"
        ],
        "pass": "1pass",
        "fail": "1fail"
      },
      {
        "id": "1pass",
        "type": "m",
        "p": "Your soothing energy calms the dragon, and he lets you approach. You're able to bandage his wounds.<br><br>You feel like your magic is getting stronger.",
        "mod": [
          "@C",
          "1 EFFECT_FACE_ADD_HEART"
        ],
        "n": "e"
      },
      {
        "id": "1fail",
        "type": "m",
        "p": "The angry dragon flails and breaths crazy amounts fire.  You barely manage to escape unscathed!<br><br>The villager rushes him away, shouting about how much you upset his pet.<br><br>After this debacle, you know the Black Cat is very displeased with you.",
        "mod": [
          "-1 FAVOR_CAT"
        ],
        "n": "e"
      },
      {
        "id": "2a",
        "type": "m",
        "p": "@L1",
        "mod": [
          "-@B1",
          "@C",
          "@E"
        ],
        "n": "e"
      },
      {
        "id": "2b",
        "type": "m",
        "p": "@L1",
        "mod": [
          "-@B2",
          "@C",
          "@E"
        ],
        "n": "e"
      },
      {
        "id": "3",
        "type": "m",
        "p": "\"Some witch you are!\"<br><br>The villager spits at you and leaves with his dragon.<br><br>You can sense the Black Cat's displeasure.",
        "mod": [
          "-@E"
        ],
        "n": "e"
      }
    ],
    "vars": {
      "@A": {
        "str": "HEART(1)"
      },
      "@B1": {
        "str": "1 POT_DRAGON_SWEAT"
      },
      "@B2": {
        "str": "ING(1 POT_DRAGON_SWEAT)"
      },
      "@L1": {
        "str": "The angry dragon breaths streams of fire, but the potion protects you as you heal him.  The villager is grateful and rewards you for your effort."
      },
      "@L2": {
        "str": "with that you can get close without issue."
      },
      "@C": {
        "str": "10 GOLD"
      },
      "@E": {
        "str": "1 FAVOR_CAT"
      }
    }
  },
  {
    "title": "You Have a Cold",
    "icon": "🤧",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "You feel groggy and sick this morning, and it's a struggle to get out of bed.",
        "choices": [
          {
            "text": "You're not feeling well, and simply cannot be a proper witch today.",
            "n": "1"
          },
          {
            "text": "Drink @A.",
            "conditionText": "HAS(@A)",
            "n": "2"
          },
          {
            "text": "Mix @A and drink it.",
            "conditionText": "HAS_I(@A)",
            "n": "3"
          }
        ]
      },
      {
        "id": "1",
        "type": "m",
        "p": "You should feel better soon, but not today.",
        "mod": [
          "1 EFFECT_COLD"
        ]
      },
      {
        "id": "2",
        "type": "m",
        "p": "You drink @A and feel better.<br><br>...@L",
        "mod": [
          "-@A",
          "1 EFFECT_GREEN_THUMB"
        ],
        "n": "e"
      },
      {
        "id": "3",
        "type": "m",
        "p": "You mix @A and drink it.<br><br>You feel better.<br><br>...@L",
        "mod": [
          "-@B",
          "1 EFFECT_GREEN_THUMB"
        ],
        "n": "e"
      }
    ],
    "vars": {
      "@A": {
        "str": "1 POT_COLD_CURE"
      },
      "@B": {
        "str": "ING(1 POT_COLD_CURE)"
      },
      "@L": {
        "str": "A lot better!  You feel like you can harvest extra today!"
      }
    }
  },
  {
    "title": "Green Thumbs",
    "icon": "🌱",
    "children": [
      {
        "id": "0",
        "type": "m",
        "p": "Today is a good day!  You woke up with green thumbs!",
        "mod": [
          "1 EFFECT_GREEN_THUMB"
        ],
        "n": "e"
      }
    ],
    "vars": {}
  },
  {
    "title": "Cursed Robbery!",
    "icon": "🦹‍♂️",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "A costumed man dashes into your shop.<br><br>\"Give me all your money or I'll curse you!\"",
        "choices": [
          {
            "text": "Cower and give him @A.",
            "n": "1"
          },
          {
            "text": "Stand your ground. @B",
            "n": "2"
          },
          {
            "text": "Reason with him. @C",
            "n": "3"
          }
        ]
      },
      {
        "id": "1",
        "type": "m",
        "p": "You empty your coffers and give up @A.",
        "mod": [
          "-@A"
        ],
        "n": "e"
      },
      {
        "id": "2",
        "type": "d",
        "p": "You raise your hands...",
        "rolls": [
          "@B"
        ],
        "pass": "2pass",
        "fail": "2fail"
      },
      {
        "id": "2pass",
        "type": "m",
        "p": "Your spell terrifies the would-be robber, who scurries away, dropping some coins on the floor.",
        "mod": [
          "5 GOLD"
        ],
        "n": "e"
      },
      {
        "id": "2fail",
        "type": "m",
        "p": "He has a trick up his sleeve!  He raises his hands and, after a flash, you fall to the ground, feeling ill!<br><br> After a struggle, you are barely able to fend him off and he leaves.",
        "mod": [
          "1 EFFECT_REPLACE_CURSE",
          "-3 GOLD"
        ],
        "n": "e"
      },
      {
        "id": "3",
        "type": "d",
        "p": "You raise your hands...",
        "rolls": [
          "@C"
        ],
        "pass": "3pass",
        "fail": "2fail"
      },
      {
        "id": "3pass",
        "type": "m",
        "p": "You reason with the man, and he is impressed by your wisdom.  He, miraculously, leaves you with a generous tip.",
        "mod": [
          "10 GOLD"
        ],
        "n": "e"
      }
    ],
    "vars": {
      "@A": {
        "str": "ALL GOLD"
      },
      "@B": {
        "str": "FIRE(2)"
      },
      "@C": {
        "str": "HEART(2)"
      }
    }
  },
  {
    "title": "Mason",
    "icon": "🧱",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "A mason visits you. He offers to upgrade your garden for @D.",
        "choices": [
          {
            "text": "@L2<br>@A.",
            "conditionText": "HAS(@D)",
            "n": "1a"
          },
          {
            "text": "@L2<br>@B.",
            "conditionText": "HAS(@D)",
            "n": "1b"
          },
          {
            "text": "@L2<br>@C.",
            "conditionText": "HAS(@D)",
            "n": "1c"
          },
          {
            "text": "No thanks.",
            "n": "4"
          }
        ]
      },
      {
        "id": "1a",
        "type": "m",
        "p": "@L1",
        "mod": [
          "-@D",
          "@A"
        ],
        "n": "e"
      },
      {
        "id": "1b",
        "type": "m",
        "p": "@L1",
        "mod": [
          "-@D",
          "@B"
        ],
        "n": "e"
      },
      {
        "id": "1c",
        "type": "m",
        "p": "@L1",
        "mod": [
          "-@D",
          "@C"
        ],
        "n": "e"
      },
      {
        "id": "4",
        "type": "m",
        "p": "He leaves.",
        "n": "e"
      }
    ],
    "vars": {
      "@A": {
        "str": "1 BLUEPRINT_SPARKLEWEED"
      },
      "@B": {
        "str": "1 BLUEPRINT_BRAMBLEBERRY"
      },
      "@C": {
        "str": "1 BLUEPRINT_SPECIALPETAL"
      },
      "@D": {
        "str": "5 GOLD"
      },
      "@L1": {
        "str": "Before the day is done you have a lovely new addition to your garden."
      },
      "@L2": {
        "str": "Build a bed for"
      }
    }
  },
  {
    "title": "Herb Merchant",
    "icon": "🛒",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "A traveling merchant visits. \"Got a surplus of plants.  I can give ya a good deal.\"",
        "choices": [
          {
            "text": "Trade @A1 for<br>@A2.",
            "conditionText": "HAS(@A1)",
            "n": "1"
          },
          {
            "text": "Trade @B1 for<br>@B2.",
            "conditionText": "HAS(@B1)",
            "n": "2"
          },
          {
            "text": "Decline the offer",
            "n": "e"
          }
        ]
      },
      {
        "id": "1",
        "type": "m",
        "p": "@L",
        "mod": [
          "-@A1",
          "@A2"
        ],
        "n": "e"
      },
      {
        "id": "2",
        "type": "m",
        "p": "@L",
        "mod": [
          "-@B1",
          "@B2"
        ],
        "n": "e"
      }
    ],
    "vars": {
      "@A1": {
        "str": "GOLD(RAND1_2)"
      },
      "@A2": {
        "str": "HERB1(RAND3_4)"
      },
      "@B1": {
        "str": "GOLD(RAND2_3)"
      },
      "@B2": {
        "str": "HERB2(RAND2_3)"
      },
      "@L": {
        "str": "You make the trade."
      }
    }
  },
  {
    "title": "Attack!",
    "icon": "😈",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "A monster is attacking the village! As a witch, it is your duty to help.",
        "choices": [
          {
            "text": "Fend off the monster with your magic.<br>@A",
            "n": "1"
          },
          {
            "text": "Maybe diplomacy will work this time.<br>@B",
            "n": "2"
          }
        ]
      },
      {
        "id": "1",
        "type": "d",
        "p": "You prepare to launch a spell at the monster.",
        "rolls": [
          "@A"
        ],
        "pass": "1pass",
        "fail": "1fail"
      },
      {
        "id": "1pass",
        "type": "m",
        "p": "With the villagers help, you manage to fend off the monster.<br><br>@L",
        "mod": [
          "5 GOLD"
        ],
        "n": "e"
      },
      {
        "id": "1fail",
        "type": "m",
        "p": "Your spell is not enough, and after a long battle, the monster is finally fended off by the villagers.  Bedraggled and exhausted, you return to your shop.<br><br>The Black Cat is displeased with your performance.",
        "mod": [
          "-@C"
        ],
        "n": "e"
      },
      {
        "id": "2",
        "type": "d",
        "p": "With eyes closed, you reach out to the monster's chaotic mind with your magic.",
        "rolls": [
          "@B"
        ],
        "pass": "2pass",
        "fail": "1fail"
      },
      {
        "id": "2pass",
        "type": "m",
        "p": "Your spell sooths the monster just enough for you to get it to decide to leave peacefully.<br><br>@L",
        "mod": [
          "@C",
          "7 GOLD"
        ],
        "n": "e"
      }
    ],
    "vars": {
      "@A": {
        "str": "FIRE(1)"
      },
      "@B": {
        "str": "HEART(2)"
      },
      "@C": {
        "str": "1 FAVOR_CAT"
      },
      "@L": {
        "str": "The grateful villagers scrounge together a nice reward for you."
      }
    }
  },
  {
    "title": "Villager Contract",
    "icon": "📜",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "A villager comes to your shop and requisitions a potion:<br><br>@A.",
        "choices": [
          {
            "text": "Sell the potion for<br>@B.",
            "conditionText": "HAS(@A)",
            "n": "1"
          },
          {
            "text": "You can mix it and sell it right now for<br>@B.",
            "conditionText": "HAS_I(@A)",
            "n": "2"
          },
          {
            "text": "Say that you'll have the potion ready by next week.",
            "n": "3"
          }
        ]
      },
      {
        "id": "1",
        "type": "m",
        "p": "The villager buys the potion and leaves.",
        "mod": [
          "-@A",
          "@B"
        ],
        "n": "e"
      },
      {
        "id": "2",
        "type": "m",
        "p": "The villager buys the potion and leaves.",
        "mod": [
          "-@D",
          "@B"
        ],
        "n": "e"
      },
      {
        "id": "3",
        "type": "m",
        "p": "The villager leaves, promising to return next week.",
        "n": "e",
        "mod": [
          "1 CONTRACT_VILLAGER"
        ]
      }
    ],
    "vars": {
      "@A": {
        "str": "POT1(1)"
      },
      "@B": {
        "str": "9 GOLD"
      },
      "@C": {
        "str": "1 FAVOR_CAT"
      },
      "@D": {
        "str": "ING(@A)"
      }
    }
  },
  {
    "title": "Demonic Deal",
    "icon": "👹",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "You notice a pair of eyes watching you from the shadows. When you turn to stare, a smiling demon reveals itself.<br><br>\"Would you like a deal, my dear?\"",
        "choices": [
          {
            "text": "Add @A1<br>AND<br>add @A2.",
            "n": "1"
          },
          {
            "text": "No thanks.",
            "n": "2"
          }
        ]
      },
      {
        "id": "1",
        "type": "m",
        "p": "@L",
        "mod": [
          "@C",
          "@D"
        ],
        "n": "e"
      },
      {
        "id": "2",
        "type": "m",
        "p": "It leaves.",
        "n": "e"
      }
    ],
    "vars": {
      "@A1": {
        "str": "1"
      },
      "@A2": {
        "str": "1 DICE_CURSE"
      },
      "@C": {
        "str": "1"
      },
      "@D": {
        "str": "1 EFFECT_FACE_ADD_CURSE"
      },
      "@L": {
        "str": "The demon snaps its fingers, and you feel something fundamental change within you."
      }
    }
  },
  {
    "title": "The Black Cat",
    "icon": "🐈‍⬛",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "The Black Cat suddenly appears.<br><br>\"Tribute. @A. I demand it.\"",
        "choices": [
          {
            "text": "Give the gold to the Black Cat.",
            "conditionText": "HAS(@A)",
            "n": "1"
          },
          {
            "text": "Say that you can't.",
            "n": "fail"
          }
        ]
      },
      {
        "id": "1",
        "type": "m",
        "p": "With a mischievous grin, The Black Cat gathers the gold.<br><br>\"Much appreciated, now I shall grant you a boon.\"",
        "mod": [
          "-@A"
        ],
        "n": "ch"
      },
      {
        "id": "ch",
        "type": "ch",
        "p": "\"What would you like?\""
      },
      {
        "id": "fail",
        "type": "m",
        "p": "\"I see,\" The Black Cat says. \"Do not disappoint me again. Despite this, I shall grant you a boon. Maybe next time you won't fail.\"",
        "mod": [
          "-@B"
        ],
        "n": "ch"
      }
    ],
    "vars": {
      "@A": {
        "str": "GOLD(RAND2_4)"
      },
      "@B": {
        "str": "1 FAVOR_CAT"
      },
      "@L1": {
        "str": "The Black Cat's eyes glow"
      },
      "@L2": {
        "str": "and new seed bed appears in your garden."
      }
    }
  },
  {
    "title": "The Final Test",
    "icon": "🐈‍⬛",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "The Black Cat suddenly appears.<br><br>\"I have a final test for you.  Demonstrate your magic to me.\"",
        "choices": [
          {
            "text": "Cast a threatening fire spell.<br>@A",
            "n": "1"
          },
          {
            "text": "Cast a soothing heart spell.<br>@B",
            "n": "2"
          },
          {
            "text": "Give the cat the money you've earned, surely @C is enough.",
            "conditionText": "HAS(@C)",
            "n": "3"
          }
        ]
      },
      {
        "id": "1",
        "type": "d",
        "p": "@L1",
        "rolls": [
          "@A"
        ],
        "pass": "1pass",
        "fail": "1fail"
      },
      {
        "id": "1pass",
        "type": "m",
        "p": "@L2",
        "n": "e"
      },
      {
        "id": "1fail",
        "type": "m",
        "p": "@L3",
        "mod": [
          "-ALL FAVOR_CAT",
          "1 EFFECT_COLD"
        ],
        "n": "e"
      },
      {
        "id": "2",
        "type": "d",
        "p": "@L1",
        "rolls": [
          "@B"
        ],
        "pass": "1pass",
        "fail": "1fail"
      },
      {
        "id": "3",
        "type": "m",
        "p": "\"A bargain?\"  The cat makes a gagging sound that could almost have been a laugh.  \"Very well, I accept.\"",
        "mod": [
          "-@C"
        ],
        "n": "e"
      }
    ],
    "vars": {
      "@A": {
        "str": "FIRE(3)"
      },
      "@B": {
        "str": "HEART(3)"
      },
      "@C": {
        "str": "GOLD(10)"
      },
      "@L1": {
        "str": "You prepare to cast a spell to impress the Black Cat."
      },
      "@L2": {
        "str": "The Black Cat emits a soft purr of satisfaction.  \"Very good.  When I return, surely you will be rewarded.\""
      },
      "@L3": {
        "str": "The fur stands on end as the Black Cat's eyes glow red.  \"This is not the work of a true witch.\""
      }
    }
  },
  {
    "title": "Expulsion",
    "icon": "🐈‍⬛",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "The Black Cat appears in front of you and stares you down with disappointed eyes.<br><br>\"I now see that you are not worthy of witchhood.\"<br><br>A tugging, a pulling, a ripping sensation engulfs you, tearing out your insides, eviscerating your soul. You're left unconscious on the ground with nothing.  No gold.  No potions.  No magic.<br><br>You are no longer a witch.",
        "choices": [
          {
            "text": "Try again.",
            "n": "1"
          },
          {
            "text": "Quit.",
            "conditionText": "HAS(999 GOLD)",
            "n": "1"
          }
        ]
      },
      {
        "id": "1",
        "type": "m",
        "mod": [
          "1 EFFECT_RELOAD"
        ]
      }
    ],
    "vars": {}
  },
  {
    "title": "True Witch",
    "icon": "🐈‍⬛",
    "children": [
      {
        "id": "0",
        "type": "ch",
        "p": "\"That's enough,\" says the Black Cat. \"I'm pleased with you. You may keep your magic.\"<br><br>Congratulations! You've completed the game.<br><br>Would you like to play again?",
        "choices": [
          {
            "text": "Yes.",
            "n": "1"
          },
          {
            "text": "No.",
            "conditionText": "HAS(999 GOLD)",
            "n": "1"
          }
        ]
      },
      {
        "id": "1",
        "type": "m",
        "mod": [
          "1 EFFECT_RELOAD"
        ]
      }
    ],
    "vars": {}
  }
];
